### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by Urkman** [vl4dimir/ObjectiveMixin#12]
Is this project still alive?
Does it makes sense to use it in an Xcode5, iOS8 project?

**Comment by vl4dimir** [comment]
Yes, it's alive. I haven't been actively developing iOS applications for a couple of years, but I'm still accepting pull requests and doing "gardening" of the project.

If you find an issue with Xcode 5 + iOS 8 combo, I'd appreciate it if you report the bug here, or even better submit a bugfix as a pull request. :)
